language: node_js

node_js:
  - '7.4'

install:
  - npm install

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm run test:ci"
    - CI_ACTION="npm run lint"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
